# This is a config for E2B sandbox template.
# You can use template ID (3mugjavt415eyau51u81) or template name (codezap-nextjs-testcase-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codezap-nextjs-testcase-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("codezap-nextjs-testcase-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codezap-nextjs-testcase-1')

team_id = "8f7b7f70-4cfd-424b-aaf0-2b858f1a9f53"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codezap-nextjs-testcase-1"
template_id = "3mugjavt415eyau51u81"
